# Path to your dotfiles.
export DOTFILES=$HOME/.dotfiles

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export ZSH_CUSTOM=$DOTFILES

# Enable completions
autoload -Uz compinit && compinit


ZSH_THEME="sivam"

HIST_STAMPS="dd.mm.yyyy"


# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  docker
  github
  brew
  node
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source $DOTFILES/.aliases
source $DOTFILES/fn/functions
source $DOTFILES/fn/agam
source $DOTFILES/fn/cloud

if [ -f $DOTFILES/.aliases.work ]; then
  source $DOTFILES/.aliases.work
fi

# prevent commands from being added to your history by prepending a space to the line.
setopt HIST_IGNORE_SPACE


# GoLang
export GO_HOME="$HOME/go"
export PATH=$PATH:$GO_HOME/bin
export AWS_SESSION_TTL=12h
export AWS_ASSUME_ROLE_TTL=12h


# pnpm
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

eval "$(mise activate zsh)"

# Initialize modern CLI tools (if installed)
if command -v fzf &> /dev/null; then
  eval "$(fzf --zsh)"
fi

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
  alias cd='z'
fi

if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi
